name: Lint

on: pull_request

jobs:
  lint:
    name: Run linters on PR
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: lint
        run: "cd apollo && yarn run lint"
        working-directory: apollo
